function [d,lambda] = importSpectrum(directory, type, filename, interpAxis, dataLines)
%IMPORTFILE Import data from a text file
%  ACEMNEON = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  ACEMNEON = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  AcemNeon = importfile("C:\Users\Simon\Desktop\MATLAB\00_MyCodeAnalysis\TEMPOKevinCode\TEMPO\AllSpectrum\AcemNeon.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Jan-2020 18:26:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 5
    dataLines = [2, Inf]; % assume header in the file
end

interp=1;
if nargin <4
    interp=0;
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["lambda", "exc", "em"];
opts.VariableTypes = ["double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

fullname=fullfile(directory, type, filename);
% Import the data
Datatemp = readtable(fullname, opts);

% Convert to output type
Datatemp = table2array(Datatemp);

% find and remove NaN column
temp=sum(isnan(Datatemp),1)/size(Datatemp,1);

idx=temp==1;
Datatemp(:,idx)=[];
Data=Datatemp;

idx=~isfinite(Data);
Data(idx)=0;

% if strcmp('Proteins', type) || strcmp('Illumination', type)
Data(:,2:end)=Data(:,2:end)./max(Data(:,2:end));
Data(:,1)=round(Data(:,1)*10,0);% to deal with non-finite data point

lambda=400:800;
d=interp1(Data(:,1),Data(:,2:end),lambda*10);

% end
end